### PR TITLE
GCP: add user_agent to cloudaux

### PR DESCRIPTION
**Pull request by supertom**
This PR adds user_agent support to the various GCP clients.

### CODE REVIEW

**Comment by monkeysecurity** [comment]
test is failing

**Comment by supertom** [comment]
@monkeysecurity thanks for the catch and sorry I missed that.  Updated the tests.

**Comment by monkeysecurity** [comment]
Need to bump version and push to pypi.

**Comment by monkeysecurity** [comment]
`1.1.6` pushed to pypi.

**Pull request merged**
