### PR TITLE
Added new features for S3 Analytics 📊

### PR DESCRIPTION
**Pull request by mikegrima**
Addresses #10 

- This also updates the `@pagination` decorator to specify custom pagination markers, since the AWS API is not consistent with how it names this.
- Also updates the boto3 dependency to reflect the version that supports these API calls.

### CODE REVIEW

**Comment by mikegrima** [comment]
Going to perform a test with Security Monkey to ensure that everything works properly.

**Comment by mikegrima** [comment]
Tested successfully, ready to merge!

**Comment by monkeysecurity** [comment]
Sweet chicken.  Looks good.

**Comment by monkeysecurity** [comment]
1.0.6 published to pypi

**Pull request merged**
