### PR TITLE
Adding OpenStack cloud support

### PR DESCRIPTION
**Pull request by mstair**
Cloudaux and orchestration for OpenStack clouds

### CODE REVIEW

**Comment by mcpeak** [comment]
Looks like a nice PR.  Which versions of OpenStack does this support/target?  

Also, looking at the current docs: https://developer.openstack.org/api-ref/network/v2/index.html#list-security-groups it looks like there is at least one field you don't have (tenant_id), is that intentional?

**Comment by mstair** [comment]
Thanks, I have tested it on Kilo, Mitaka (older versions) and Pike. We have instances at various versions which is why I intentionally made it more dynamic to support older releases (which leads to your next question).

I think you are referencing my OpenStack->AWS rule translation so I could reuse the AWS security group auditor. That simply mapping the naming convention, the other security group fields remain (such as tenant_id), see example below:

```
  "rules": [
    {
      "rule_type": "ingress",
      "remote_group_id": null,
      "from_port": 22,
      "description": "",
      "tags": [],
      "to_port": 22,
      "ethertype": "IPv4",
      "created_at": "2017-09-15T12:22:30Z",
      "updated_at": "2017-09-15T12:22:30Z",
      "security_group_id": "c8a0c4f9-ce5a-4061-9782-da31a0048580",
      "revision_number": 0,
      "tenant_id": "3bb7e8e8e01247ea9401dced0a642093",
      "project_id": "3bb7e8e8e01247ea9401dced0a642093",
      "id": "723a9e91-15e1-4586-b242-72fe54560504",
      "cidr_ip": "0.0.0.0/0",
      "ip_protocol": "tcp"
    }
```
Also note that OpenStack is migrating to using project vs tenant in the newer APIs.

**Comment by mcpeak** [comment]
@mstair Sounds good, and great work!

**Comment by monkeysecurity** [comment]
Cloudaux 1.4.0 has been pushed to pypi.

**Pull request merged**
